# Generated by Django 2.1.3 on 2018-12-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='product',
            new_name='products',
        ),
        migrations.RemoveField(
            model_name='client',
            name='picture',
        ),
        migrations.AddField(
            model_name='client',
            name='profil_picture',
            field=models.ImageField(default='static/images/ecran.png', upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
