# Generated by Django 2.1.3 on 2018-12-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_auto_20181209_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='profil_picture',
            field=models.ImageField(default='static/images/profile.jpg', upload_to='static/images/profiles_pictures/'),
        ),
    ]
