# Generated by Django 2.1.3 on 2018-12-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_auto_20181210_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='profil_picture',
            field=models.ImageField(default='static/images/profile.jpg', upload_to='static/images/profiles_picture/'),
        ),
    ]
